name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn build
      - run: |
          git config --local user.email "mhankin@utexas.edu"
          git config --local user.name "Michael Hankin"
      - run: yarn deploy
